version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: infra-db
    environment:
      POSTGRES_DB: TaskListDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: $3nh@
    ports:
      - "5437:5437"